export const navigation: string;
export const menu: string;
export const upper: string;
export const notSignedIn: string;
export const login: string;
export const podcaster: string;
export const divider: string;
export const lower: string;
export const version: string;
